### ISSUE TITLE
Changing console unit to the mystery spongebob breaks the console

### ISSUE THREAD

**Issue by honestcactus** [CommandrMoose/Masters-Delight#3]
It changes the console into a missing textures block and I lose almost all interactions with it.

Cannot change it back nor can I change the interior or anything, really.

![image](https://user-images.githubusercontent.com/19522057/95640469-905cb680-0a62-11eb-81ae-0e632ef21cc0.png)
![image](https://user-images.githubusercontent.com/19522057/95640476-98b4f180-0a62-11eb-8bc9-d00d443f5c87.png)

**Comment by CommandrMoose** [comment]
Hey there! Thanks for the report. This was an accidental addition that was unfinished. If you have access to commands, you can run
_/setblock 0 128 0 tardis:console_steam_ and _/tardis setup_ to get your ship working again.
